name: Companion Module Checks

on:
  push:

jobs:
  check:
    name: Check module

    if: ${{ !contains(github.repository, 'companion-module-template-') }}

    permissions:
      packages: read

    uses: bitfocus/actions/.github/workflows/module-checks.yaml@main
    # with:
    #   upload-artifact: true # uncomment this to upload the built package as an artifact to this workflow that you can download and share with others

  test:
    name: Unit tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: Run tests
        run: yarn test

